// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlslS6LGP1Wbne6unnjztEg8RvMzST3j4',
    appId: '1:942584945595:ios:bdc7222897c0f4a215829e',
    messagingSenderId: '942584945595',
    projectId: 'ramily-845f9',
    databaseURL: 'https://ramily-845f9-default-rtdb.firebaseio.com',
    storageBucket: 'ramily-845f9.firebasestorage.app',
    iosBundleId: 'com.example.ramily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlslS6LGP1Wbne6unnjztEg8RvMzST3j4',
    appId: '1:942584945595:ios:bdc7222897c0f4a215829e',
    messagingSenderId: '942584945595',
    projectId: 'ramily-845f9',
    databaseURL: 'https://ramily-845f9-default-rtdb.firebaseio.com',
    storageBucket: 'ramily-845f9.firebasestorage.app',
    iosBundleId: 'com.example.ramily',
  );

}